apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: mern-crud_server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: mongodb://mongo:27017/MERN
